version: '3.8'

services:
  app:
    build: 
      context: ../
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ../.env
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: metrics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
