// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Metrics_UpdateParam_FullMethodName     = "/grpc.Metrics/UpdateParam"
	Metrics_UpdateJSON_FullMethodName      = "/grpc.Metrics/UpdateJSON"
	Metrics_UpdateBatchJSON_FullMethodName = "/grpc.Metrics/UpdateBatchJSON"
)

// MetricsClient is the client API for Metrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsClient interface {
	UpdateParam(ctx context.Context, in *PostMetricRequest, opts ...grpc.CallOption) (*PostMetricResponse, error)
	UpdateJSON(ctx context.Context, in *PostMetricRequest, opts ...grpc.CallOption) (*PostMetricResponse, error)
	UpdateBatchJSON(ctx context.Context, in *BatchPostMetricRequest, opts ...grpc.CallOption) (*BatchPostMetricResponse, error)
}

type metricsClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsClient(cc grpc.ClientConnInterface) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) UpdateParam(ctx context.Context, in *PostMetricRequest, opts ...grpc.CallOption) (*PostMetricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostMetricResponse)
	err := c.cc.Invoke(ctx, Metrics_UpdateParam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) UpdateJSON(ctx context.Context, in *PostMetricRequest, opts ...grpc.CallOption) (*PostMetricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostMetricResponse)
	err := c.cc.Invoke(ctx, Metrics_UpdateJSON_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) UpdateBatchJSON(ctx context.Context, in *BatchPostMetricRequest, opts ...grpc.CallOption) (*BatchPostMetricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchPostMetricResponse)
	err := c.cc.Invoke(ctx, Metrics_UpdateBatchJSON_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServer is the server API for Metrics service.
// All implementations must embed UnimplementedMetricsServer
// for forward compatibility.
type MetricsServer interface {
	UpdateParam(context.Context, *PostMetricRequest) (*PostMetricResponse, error)
	UpdateJSON(context.Context, *PostMetricRequest) (*PostMetricResponse, error)
	UpdateBatchJSON(context.Context, *BatchPostMetricRequest) (*BatchPostMetricResponse, error)
	mustEmbedUnimplementedMetricsServer()
}

// UnimplementedMetricsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsServer struct{}

func (UnimplementedMetricsServer) UpdateParam(context.Context, *PostMetricRequest) (*PostMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParam not implemented")
}
func (UnimplementedMetricsServer) UpdateJSON(context.Context, *PostMetricRequest) (*PostMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJSON not implemented")
}
func (UnimplementedMetricsServer) UpdateBatchJSON(context.Context, *BatchPostMetricRequest) (*BatchPostMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBatchJSON not implemented")
}
func (UnimplementedMetricsServer) mustEmbedUnimplementedMetricsServer() {}
func (UnimplementedMetricsServer) testEmbeddedByValue()                 {}

// UnsafeMetricsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServer will
// result in compilation errors.
type UnsafeMetricsServer interface {
	mustEmbedUnimplementedMetricsServer()
}

func RegisterMetricsServer(s grpc.ServiceRegistrar, srv MetricsServer) {
	// If the following call pancis, it indicates UnimplementedMetricsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Metrics_ServiceDesc, srv)
}

func _Metrics_UpdateParam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).UpdateParam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_UpdateParam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).UpdateParam(ctx, req.(*PostMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_UpdateJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).UpdateJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_UpdateJSON_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).UpdateJSON(ctx, req.(*PostMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_UpdateBatchJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPostMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).UpdateBatchJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_UpdateBatchJSON_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).UpdateBatchJSON(ctx, req.(*BatchPostMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Metrics_ServiceDesc is the grpc.ServiceDesc for Metrics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metrics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParam",
			Handler:    _Metrics_UpdateParam_Handler,
		},
		{
			MethodName: "UpdateJSON",
			Handler:    _Metrics_UpdateJSON_Handler,
		},
		{
			MethodName: "UpdateBatchJSON",
			Handler:    _Metrics_UpdateBatchJSON_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
